---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# paleocar_v2

<!-- badges: start -->
<!-- badges: end -->


**DEPRECATION WARNING**

The PaleoCAR v2 dataset has been superceded by the [PaleoCAR v3 dataset](https://github.com/bocinsky/paleocar_v3). New analyses should use those data.

---

This is an archive of the PaleoCAR v2 paleoclimate reconstruction datasets originally published in Science Advances:

> R. Kyle Bocinsky, Johnathan Rush, Keith W. Kintigh and Timothy A. Kohler, 2016: Exploration and exploitation in the macrohistory of the pre-Hispanic Pueblo Southwest. Science Advances, 2(4), [DOI: 10.1126/sciadv.1501532](https://doi.org/10.1126/sciadv.1501532).

The dataset is available as tiled NetCDF files as part of the NOAA National Centers for Environmental Information Paleoclimate archive at [DOI: 10.25921/8ctk-8v26](https://doi.org/10.25921/8ctk-8v26).

The PaleoCAR v2 data are high spatial resolution (30 arc-second) Southwestern United States tree-ring reconstructions of May-September Growing-degree Days (GDD) and Net Water-year Precipitation (previous October - current September). The reconstructions were performed using the "PaleoCAR" method detailed in Bocinsky and Kohler (2014), as updated in Bocinsky et al. (2016).

The script in this repository downloads the archived tiled data, mosaics them together, writes them as cloud-optimized GeoTiffs, and uploads them to an Amazon AWS S3 bucket at [https://skope.s3.us-west-2.amazonaws.com/index.html](https://skope.s3.us-west-2.amazonaws.com/index.html). These files are then able to be queried remotely.
